### ISSUE TITLE
Improve “Element Queries”

### ISSUE THREAD

**Issue by rickmills** [craftcms/docs#114]
I have a suggestion for https://craftcms.com/docs/3.x/element-queries.html

The page mentions this:

> Most custom fields support element query parameters as well, named after the field handles. See each field type’s documentation for examples.

Using that as an example, I go to the plain text field expecting to see an example of how to use a custom field using that type in an Element (not Entry) query, but theres no such examples.

Either the quoted text needs removing, or more preferably there needs to be an example of using custom fields with Elements (again, not Entries) as there doesn't appear to be any examples on how to query an Element by custom fields right now.

As a rough example of real-world need for this, if you've got a custom field on an Element in one of your own plugins (E.g Digital Products or Commerce) there is then no documentation on how you would query that custom field.

It'd be really beneficial if this page could provide some examples, as even [a Google search](https://www.google.com/search?q=craftcms+query+element+by+custom+field) is only returning how to do it with an Entry which looks to be a different process.

**Comment by mattstein** [comment]
Thanks for the feedback, @rickmills.

> Using that as an example, I go to the plain text field expecting to see an example of how to use a custom field using that type in an Element (not Entry) query, but theres no such examples.

How would you expect to limit an element query by a field that stores plain text? There are examples of how you can use the [search syntax](https://craftcms.com/docs/3.x/searching.html) in element queries if your intent is to search for a field with specific content, but I’m not following what makes the plain text field an ideal example.

> Using that as an example, I go to the plain text field expecting to see an example of how to use a custom field using that type in an Element (not Entry) query, but theres no such examples.

The checked field type pages below support and list their custom query parameters in the _Templating_ section:

- [x] Assets Fields
- [x] Categories Fields
- [x] Checkboxes Fields
- [ ] Color Fields
- [x] Date Fields
- [x] Dropdown Fields
- [x] Entries Fields
- [x] Lightswitch Fields
- [x] Matrix Fields
- [x] Multi-select Fields
- [x] Number Fields
- [ ] Plain Text Fields
- [x] Radio Buttons Fields
- [ ] Table Fields
- [x] Tags Fields
- [x] Time Fields
- [x] Users Fields

Custom fields on an element will behave the same regardless of the element type. So...

```twig
{% set entries = craft.entries()
    .myFieldHandle(':notempty:')
    .all() %}
```

...with Commerce Products instead of Entries—using the exact same field—would become...

```twig
{% set products = craft.products()
    .myFieldHandle(':notempty:')
    .all() %}
```

Nothing changes about the field handle or any relevant parameters it supports.

Am I missing your point, or is there something about how this is all explained in the docs that could be more clear?

**Comment by rickmills** [comment]
Thanks for the quick reply @mattstein!

So the issue I had when I came to the docs page was that I've got a custom module to update Digital Products, so need to be able to query the Products in the Digital Products plugin, searching by a custom field that contains a unique reference. 

Whilst I could find docs on searching something in twig that was an entry I couldn't see anything for things like products. 

The second example you posted above does look to be what I'm after though, so presumably that means something along the lines of this should work?

```php
use craft\digitalproducts\Plugin;

$product = Plugin::getInstance()->getProducts()->myCustomFieldName('someVar')->one();
```

I guess the bit of documentation I'm missing is an explainer on how you perform a query with custom fields on something other than an Entry like Products which seem to be Elements, but I'm possibly looking in the wrong place? 

Thanks again for your time.

**Comment by mattstein** [comment]
> The second example you posted above does look to be what I'm after though, so presumably that means something along the lines of this should work?

Nearly yes with a big asterisk.

`craft.entries()`, `craft.products()` each return an entry query. Per that first example on the _Entry Queries_ page, it looks slightly different in PHP where the element’s `find()` method returns the query object you customize.

> Whilst I could find docs on searching something in twig that was an entry I couldn't see anything for things like products.

Maybe you’re looking for [this page](https://craftcms.com/docs/commerce/3.x/dev/element-queries/product-queries.html)?

I’m guessing the fuzzy part is understanding how these entry queries are common across element types. Here’s what I mean:

## Craft Entries

```php
use craft\elements\Entry;

$entryQuery = Entry::find()
    ->myCustomFieldName('someVar')
    ->section('news')
    ->orderBy('postDate desc')
    ->limit(10);

$entries = $entryQuery->all();
```

## Commerce Products

```php
use craft\commerce\elements\Product;

$productQuery = Product::find()
    ->myCustomFieldName('someVar')
    ->type('bar')
    ->orderBy('dateCreated desc')
    ->limit(10);

$products = $productQuery->all();
```

## Digital Products

```php
use craft\digitalproducts\elements\Product;

$digitalProductQuery = Product::find()
    ->myCustomFieldName('someVar')
    ->type('bar')
    ->orderBy('dateCreated desc')
    ->limit(10);

$digitalProducts = $digitalProductQuery->all();
```

## *⃣ Big Asterisk

For `myCustomFieldName('someVar')` to work as you expect, the element type doesn’t matter but the custom field you use needs to be...

1. From Craft or a plugin, with support for taking `'someVar'` as a query parameter and behaving as you expect.
2. A custom field type you add yourself, using `modifyElementsQuery()` in order to take `'someVar'` as a parameter and have it affect the query like you intend. The Lightswitch field has [a nice, simple example of this](https://github.com/craftcms/cms/blob/master/src/fields/Lightswitch.php#L182-L192), translating the element query parameter into a condition for the database query.

**Comment by rickmills** [comment]
Excellent, that helps massively, thanks a ton @mattstein !
