### ISSUE TITLE
Commerce Docs updates

### ISSUE THREAD

**Issue by lukeholder** [craftcms/docs#123]
The following are notes on the new Commerce docs.

I am yet to look through the Extending Commerce docs.

#### Customers List

- [x] Use CP navigation path to this ‘Customer List’ ?
`commerce > customers` 

#### Address Lines

- [x] Should address lines  be in this customers page or addresses page? 

#### Variant Properties

- [x] Fix missing screenshot
> TODO: screenshot single-variant UI + multi-variant UI

### Order Carts https://craftcms.com/docs/commerce/3.x/orders-carts.html

- [x] Replace:

> When we use the terms “cart” and “order”, we’re always referring to an element; a cart is simply an order that hasn’t been completed—meaning its isCompleted property is false.	

with something like

meaning its isCompleted property is false, and the dateCompleted is `null`

- [x] Replace:

> To see what cart information you can use in your templates, take a look at the Order (opens new window)class reference. You can also see sample Twig in the example templates’ shop/cart/index.twig (opens new window).

with something like

Maybe we add the main properties of an order here?

- order.lineItems
- order.adjustments
- order.customer
- order.user
-  etc?

If we don’t list the properties, maybe we make a overview of the the main things an order contains ?

- [x] Replace:

> The `cartUpdatedNotice` parameter

with 

The the new standard `successMessage` parameter Craft now offers
Maybe link to the craft docs on this param?
Also need to update across all docs pages.

- [x] Replace:

Screenshot
> The note and options will be visible on the order’s detail page in the control panel:
> https://craftcms.com/docs/assets/img/lineitem-options-review.1af6436a.png

with an

Update screenshot

- [x] Fix broken url
“navigating to a URL” link in the Load Cart section

### Sales https://craftcms.com/docs/commerce/3.x/sales.html

- [x] Replace:

> Store Owner 

with

Store Manager

- [x] Add information on the `commerce-managePromotions` permission next to the mention of store managers managing the sales.

#### Sales Templating

- [x] Link to sales model in API docs so they know what sale attributes to use to output sale info

### Discounts https://craftcms.com/docs/commerce/3.x/discounts.html

- [x] Add information on the `commerce-managePromotions` permission next to the mention of store managers managing the discounts.

- [x] Replace:

> Inside the condition formula you have access to the order variable.

with

Inside the condition formula you have access to the order variable. The order variable is actually as an array, not the order element model. It is generated with:

`$order->toArray([], ['lineItems.snapshot', 'shippingAddress', 'billingAddress'])

most variables are available accessed the same way as using the model, but this limitation prevents store managers from calling methods on the order model like `order.markAsComplete()` accidentally.

#### Discount Templating

- [x] Link to discount model in API docs so they know what sale attributes to use to output discount info

### Emails https://craftcms.com/docs/commerce/3.x/emails.html

- [x] Mention emails can be sent from the order edit page also, and don’t need to be attached to an order status.

### PDFs https://craftcms.com/docs/commerce/3.x/pdfs.html

- [x] Mention PDFs can be downloaded from the order edit page also, and don’t need to be attached to an email.

**Comment by mattstein** [comment]
Tried some illustrative single- vs. multi-variant “screenshots” in 5df019a47c9b3ae29b3f7215ca3d5936be8a5fe9.

**Comment by mattstein** [comment]
> Mention PDFs can be downloaded from the order edit page also, and don’t need to be attached to an email.

This one’s covered in the first sentence on the page and again in _Downloading a PDF_, so I’m checking it off without any change.

**Comment by mattstein** [comment]
> Maybe we add the main properties of an order here?

@lukeholder How do you feel about this somewhat random JSON example I used on the [Addresses page](https://craftcms.com/docs/commerce/3.x/addresses.html)? As far as templating goes, I’ll usually dump something out to JSON in order to get a sense of what’s there—and being in a little arrow toggle it doesn’t hurt the page flow.

Could that work here?

![Screen Shot 2021-01-04 at 11 07 02 AM@2x](https://user-images.githubusercontent.com/2488775/103560244-111e2980-4e7d-11eb-8771-a315ba01d3e4.png)

**Comment by mattstein** [comment]
Updated `cartUpdatedNotice` → `successMessage` in e46714a0e37f2888ade04a8a1449a1dbc9a2d331. There’s no direct/obvious place to link `successMessage` in the Craft docs, but once Commerce has its own Controllers page we’ll be able to link to that liberally.

**Comment by mattstein** [comment]
> > Maybe we add the main properties of an order here?
> 
> @lukeholder How do you feel about this somewhat random JSON example I used on the [Addresses page](https://craftcms.com/docs/commerce/3.x/addresses.html)? As far as templating goes, I’ll usually dump something out to JSON in order to get a sense of what’s there—and being in a little arrow toggle it doesn’t hurt the page flow.
> 
> Could that work here?

Per discussion, should try `toArray()` representation with whatever `extraFields()` make sense. Will try in a few places and omit these examples if they’re more confusing than the API docs.

**Comment by mattstein** [comment]
https://linear.app/craftcms/issue/DOC-1/commerce-docs-updates

**Comment by mattstein** [comment]
@lukeholder We’ve been waiting on me to figure out how to display an example object because the code toggle (pictured above) performs abysmally in Chrome. I finally did this with a heigh-limited component you can expand:

![Screen Shot 2021-02-11 at 06 48 53 PM](https://user-images.githubusercontent.com/2488775/107717943-675f6300-6c9a-11eb-8950-4fdbdd918c8d.gif)

These are the two example Commerce objects, which are models `var_export()`ed and cleaned up slightly:
- https://github.com/craftcms/docs/blob/develop/docs/commerce/3.x/example-objects/storeAddress.php
- https://github.com/craftcms/docs/blob/develop/docs/commerce/3.x/example-objects/order.php

I _think_ these should work well so I’m closing this out, but you can edit either one and it’ll get pulled directly into the docs. (Feel free to edit or let me know what should change.)
