### ISSUE TITLE
suggest how to handle a non-suitable project config app

### ISSUE THREAD

**Issue by joepagan** [craftcms/docs#165]
### Description

Been a craft dev for some time on mostly v2 apps and some early v3s though only recently updated a handful to 3.6.* and found this is not obvious enough.

After going on a wild goose chase finding old search results for a deprecated config setting https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#public-properties

I believe the correct thing to do is to gitignore the project config dir contents for if the answer is no under the [Is project config support right for you?](https://craftcms.com/docs/3.x/extend/project-config.html#is-project-config-support-right-for-you) heading

**Comment by mattstein** [comment]
@joepagan I’m a little confused—you linked to the Project Config page in the Extending Craft section dealing with custom plugins and modules.

It sounds like you’re referring to the deprecated `useProjectConfig` setting and not having the Craft instance—as opposed to your plugin or module—write project config YAML. If that’s the case, you’re probably looking for this: https://craftcms.com/docs/3.x/project-config.html#manual-yaml-file-generation

Let me know if that helps or if I’ve missed your point!

**Comment by joepagan** [comment]
Hey @mattstein sorry I probably wasn't clear enough.

**My situation**

I've recently updated a craft3 site which didn't have project-config, that site has a custom plugin where dynamic values are stored in the plugin's fields, so I have realised that project config is not a viable option for this application. I didn't build. this app or the plugin so not going to have the knowledge about how it works without a review, and, feel that just because I'm updating that should I need to go in the "extending craft" part of the docs?

**My suggestion**

Coming at this fresh I don't think it's clear enough what to do in the event that project config is not the right thing for a craft app. Under the heading I highlighted it suggests:

>If the answer to any of those is “yes”

but where is the counter:

>If the answer to any of those is “no”

I googled round this topic and found a blog about the config setting I later found was deprecated, which was the only reference on what to do in that scenario.
Eventually asked on discord where I got my answer to gitignore the project config dir.

I am aware that is project config support right for you is in the extending craft section, but it was the only relevant information I could find on the topic...

**Comment by mattstein** [comment]
Thanks for clarifying, @joepagan.

For **plugins and modules**, project config is an opt-in choice for how data is stored. A plugin can use its own database tables, for example, that never touch project config—and that may or may not be a good idea depending on the use case. But that’s what custom plugins and modules choose to do with project config.

**Craft** relies on project config no matter what.

That deprecated `useProjectConfig` setting offered the misleading idea that you could opt out of using project config, which isn’t true because it’s a feature comprised of an API, sync mechanism, and YAML files. You *can* opt out of writing YAML files if you don’t want to generate them and sync changes—but you cannot disable project config because it’s a conduit for all Craft configuration.

So the reason there isn’t a “If the answer is no” is because it’s in the context of custom plugins and modules where not using project config means continuing however you already were.

Does that make sense?
