### ISSUE TITLE
Batch-setting parameters and \yii\db\Query functions

### ISSUE THREAD

**Issue by carlcs** [craftcms/docs#173]
I’m not sure if this is a bug or if it’s just not documented. Batch-setting parameters https://docs.craftcms.com/v3/dev/element-queries/#setting-parameters doesn’t work with `\yii\db\Query` functions like `addSelect()`.

**Comment by brandonkelly** [comment]
@carlcs It should work with `select`, which is the actual parameter there; `addSelect()` is just a way to append additional columns to the `select` param.

In general you’re better off chain-setting params anyway though. We mainly only allow batch-setting params because in most cases it works fine, so supporting it is one less thing you have to do when upgrading a site from Craft 2 to 3.

**Comment by carlcs** [comment]
> In general you’re better off chain-setting params anyway though. We mainly only allow batch-setting params because in most cases it works fine, so supporting it is one less thing you have to do when upgrading a site from Craft 2 to 3.

Yeah, I opened this issue because I thought something like your statement above could be worth mentioning in the batch-setting parameters warning note.
