### ISSUE TITLE
Javascript error prevents navigation

### ISSUE THREAD

**Issue by oadslug** [craftcms/docs#199]
The Craft 3 Class Reference page has a javascript error that prevents the left column nav from working at all.

https://docs.craftcms.com/api/v3/?

```
SyntaxError: Cannot declare a let variable twice: 'e'.
app.29693b84.js:8
```

Browser is Safari Version 10.1.2 (12603.3.8)
Haven't tried other browsers.

**Comment by oadslug** [comment]
Thanks @narration-sd. I checked that as well — works fine in Chrome (haven't tested Firefox). Was reporting mainly as a curtesy.

**Comment by narration-sd** [comment]
Hey Dooglas, a good move, and I was doing that too.

Meant to mention that since Quantum, Firefox has been definitely the most persnickety browser, at least in terms of the enormous lists of minor/non- issues it will mention, if these can be turned off also.  

So it might be handy actually in tracking something down that's a little obscure.
