### ISSUE TITLE
Fixed header in documentation for easy searching

### ISSUE THREAD

**Issue by siebird** [craftcms/docs#219]
A nice little UI feature would be to fix the header to the top of the screen when viewing documentation so users do not have to scroll all the way back up to perform a search.

**Comment by mattstein** [comment]
You don’t have to scroll all the way back up a page to perform a search: you can press <kbd>/</kbd> at any point to focus on the search field.

We removed the fixed header to give more space to the content you’ll presumably spend more time with, but left a hint about this shortcut:

![Screen Shot 2021-05-25 at 01 05 46 PM@2x](https://user-images.githubusercontent.com/2488775/119546910-0d227380-bd5a-11eb-8a75-d4543211ddf5.png)

Closing this since the underlying is problem solved, but let me know if you have strong feelings specifically about the fixed header as the solution.

**Comment by siebird** [comment]
I saw that and think it works well for those that navigate with keys. The animation IMO is too slow on very long pages. I still feel a fixed header is a good compromise for those that navigate with a mouse. I was looking for something specific when this came up the other day which made it cumbersome scrolling back up. Not a big deal–just a nice little touch

**Comment by mattstein** [comment]
The animation honors [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion), but doesn’t account for the time it’d take to scroll back to the top of the page. I could see that being one of the things to improve here.

I think bringing back the fixed navigation would re-introduce more visual noise to compete with the page content. Someone suggested having the search bar re-appear only when scrolling up sort of like Safari’s address bar and tabs on iOS. Will probably consider options whenever we make our next major change to the layout, FWIW.
