### ISSUE TITLE
Improve order and line item totals attribute information

### ISSUE THREAD

**Issue by lukeholder** [craftcms/docs#242]
Not sure where this should go. Likely on the https://craftcms.com/docs/commerce/3.x/orders-carts.html page

## order.total

`order.total` = `order.itemSubtotal` + `order.adjustmentsTotal`

### order.itemSubtotal

The sum of each `lineItem.subtotal`

### order.adjustmentsTotal

The sum of each `adjustment.amount` belonging to the order

<hr>

## order.itemTotal

The sum of each `lineItem.total` amount. 

### lineItem.total

`lineItem.total` = `lineItem.subtotal` + `lineitem.adjustmentsTotal`

### lineItem.subtotal

`lineItem.subtotal` = `lineItem.qty` * `lineitem.salePrice`

### lineItem.adjustmentsTotal

The sum of each `lineItem.adjustment.amount` belonging to the line item and order

<hr>

## order.totalPrice

Get the total price of the order, whose minimum value is enforced by the configured `minimumTotalPriceStrategy` setting.

default - `order.itemSubtotal` + `order.adjustmentsTotal` (which is the same as `order.total`)
zero - returns 0 if the result from 'default' would’ve been negative; minimum order total is 0.
shipping -returns the total shipping cost if the 'default' result would’ve been negative; minimum order total equals shipping amount: `order.totalShippingCost`

<hr>

### `order.adjustmentsSubtotal`

Exactly the same as `order.adjustmentsTotal`. Will be removed as a duplicate in Commerce 4

**Comment by mattstein** [comment]
Thanks @lukeholder!

I added these to the [Orders & Carts](https://craftcms.com/docs/commerce/3.x/orders-carts.html) page in their respective sections:

- Orders → [Order Totals](https://craftcms.com/docs/commerce/3.x/orders-carts.html#order-totals)
- Carts → [Line Item Totals](https://craftcms.com/docs/commerce/3.x/orders-carts.html#line-item-totals)

I’m thinking those fit best contextually.

I also briefly explained what _adjustments_ are in the [Orders](https://craftcms.com/docs/commerce/3.x/orders-carts.html#orders) introduction since we don’t mention them outside of writing custom adjusters but they’re an integral part of these totals:

> Adjustments for discounts, shipping, and tax may be applied when an order is recalcuated. Each adjustment is related to its order, and can optionally relate to a specific line item.

Lastly, I added to and reordered what you wrote here so each explanation builds on the previous one so they’re hopefully easier to understand—and linked to the [minimumTotalPriceStrategy](https://craftcms.com/docs/commerce/3.x/config-settings.html#minimumtotalpricestrategy) description rather than repeating it.
