### ISSUE TITLE
Content Migrations documentation seems incomplete

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/docs#3]
The Content Migrations documentation only explains how to run the task, but not how to actually write the migrations (or where to find the available options). Am i missing something here?

**Comment by roelvanhintum** [comment]
craftcms/cms seems the place to be for issues... https://github.com/craftcms/cms/issues/1460

**Comment by Totemika** [comment]
Same situation here. I want to code all the section and field creations for a more deterministic replication. The **UI is great for learning the possibilities** but now I want to code it and all I'm facing is errors. i.e: The example in this post [https://craftcms.com/news/craft-3-content-migrations](https://craftcms.com/news/craft-3-content-migrations) didn't work with a fresh Craft 3 installation because there seems to be an extra /app/ in the path to the functions:

![screenshot at oct 17 20-35-16](https://user-images.githubusercontent.com/4906291/31685813-3c84aac6-b37c-11e7-97cc-4f3ec331ccf5.png)

@roelvanhintum Did you manage to find a way to do this? Where should I look (I don't mind if it's the code itself but I need some basic examples).

**Comment by roelvanhintum** [comment]
I've got some answers on https://craftcms.stackexchange.com/questions/19747/has-someone-figured-out-craft-3-content-migrations. The best suggestion so far is to look into Craft's controllers and reverse engineer everything. I started working on docs for the reversed engineered examples, but have not finished yet.

**Comment by j-greig** [comment]
Any update on documentation for this? Looking at https://craftcms.stackexchange.com/questions/19747/has-someone-figured-out-craft-3-content-migrations it feels like some people smarter than me have figured it out... but I'm still a bit stuck!

**Comment by brandonkelly** [comment]
Sorry it’s taking forever. For the most part we’re just super busy getting all the critical stuff ready for the Craft 3 GA on 4/4. But to be honest. another thing is that Content Migrations is not really worthy of its name yet. In its current form it’s not well-suited for updating actual content-related things; all it’s really _great_ at right now is making schema-related changes – which is only helpful if you’re using Craft as an application framework. (For example you can see how we’re using them here: https://github.com/pixelandtonic/craftcom/tree/develop/migrations)

CM was always just a first step though. We have plans to build on it in 3.1, at which point it should get far easier to use them to keep multiple environments in sync.

**Comment by j-greig** [comment]
Thanks for the update @brandonkelly, appreciate you have a ton on at the moment.

Also I realised that I can use the Architect plugin in the meantime (would be neat if you could script this via the command line!)
