### ISSUE TITLE
Versioning/Updated Dash docsets

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/docs#34]
Currently [Dash](https://kapeli.com/dash) has Craft docsets as part of the main docset library, but they are not currently up to date (latest v2 is 2.6 and latest v3 is 3.1).

There's probably no blocker for getting 2.7 in there via the `v2` branch considering it is only receiving security updates now, but there are no dedicated branches or tags for this repo that allow for delineation between 3.2/3.3/3.4. Is this something that could be considered?

@Kapeli Is there anything else that would be required for updated Craft docsets?

**Comment by mattstein** [comment]
Good news and bad news: since you posted this issue we’ve consolidated all versions of the Craft and Commerce docs into the main branch of this repository—in addition to Nitro’s docs and the Intro to Craft CMS tutorial. Live search is also local to the project and not dependent on Algolia, so once everything’s built I’m guessing it would be easier to pull into Dash.

We’ll definitely be sticking to major versions for now though, so there’s no delineation between 3.2, 3.3, and 3.4 (etc.).

**Comment by mattstein** [comment]
Closing since we don’t have control over Dash docsets and don’t plan on changing how the docs are versioned.
