### ISSUE TITLE
Intro to Craft CMS: Asset section not updated to Craft 4

### ISSUE THREAD

**Issue by mandrasch** [craftcms/docs#401]
Hi,

just starting out with Craft CMS. Just wanted to let you know the following, guess already known:

The section https://craftcms.com/docs/getting-started-tutorial/configure/section.html#create-an-asset-volume has only a Craft v3 description and screenshot, in Craft v4 this was splitted into Assets and Volumes. 

And just as optional personal feedback: 
Personally I thought this was kind of confusing (coming from systems like WordPress where a standard media file library is already set up). It wasn't clear for me if I should set up a global media file library volume which contains all the different assets or if I should split this for each section type.

Best regards, Matthias

**Comment by AugustMiller** [comment]
Hey Matthias!

Thanks for the feedback. We're still crunching through some Craft 4.x updates, and have identified a number of places where the Tutorial lags the main documentation.

Please let us know if you hit roadblocks anywhere else—glad you've got such a keen eye, already!

**Comment by tikiatua** [comment]
Hi there, do you have any quick hints on how to register/create a custom volume in version 4? I am trying to upgrade my free internal-assets plugin to Craft 4, but the documentation on docs/docs/4.x/extend/volume-types.md still refers to the Craft 3 setup.

In short: I am trying to allow admins to restrict "public" asset access to only certain user groups, i.e. for downloads in a member only area. Ideally this could be set on the volume level, so that we can use the functionality for different types of file systems.

**Comment by AugustMiller** [comment]
Sorry for not following up on this, @tikiatua. The tutorial revisions ended up cutting a wider path around the 4.x updates, but they're finally live!

The extension docs have also been updated with some fundamentals on [Filesystem Types](https://craftcms.com/docs/4.x/extend/filesystem-types.html).

I see that you were able to get your plugin updates out, regardless—I appreciate and applaud your tenacity! ❣️
