### ISSUE TITLE
Improve “{% paginate %}”

### ISSUE THREAD

**Issue by jezthomp** [craftcms/docs#422]
I have a suggestion for https://craftcms.com/docs/2.x/templating/paginate.html

This doesnt include an example for navigating single pages.
For example you have a blog listing page that shows 6 blog posts, that navigation is fine.
However, if you click on a blog post and then within that page page you want next/previous navigation to corrosponding blog posts you cannot do that.
Infact there doesnt seem to be any instruction anywhere for it.

**Comment by AugustMiller** [comment]
Hey, Jez!

This is actually a slightly different concept from pagination. You can pass the same criteria you used for a `paginate` tag to [`entry.getNext(...)`](https://craftcms.com/docs/2.x/templating/entrymodel.html#getnext-params) and [`entry.getPrev(...)`](https://craftcms.com/docs/2.x/templating/entrymodel.html#getprev-params) to get "adjacent" entries and generate links:

```twig
{# entry.twig #}

{% indexCriteria = { section: 'blog', order: 'postDate ASC' } %}
{% set prev = entry.getPrev(indexCriteria) %}
{% set next = entry.getNext(indexCriteria) %}

<h1>{{ entry.title }}</h1>

{% if next or prev %}
  <nav>
    {% if next %}
      {{ next.getLink() }}
    {% endif %}
    {% if prev %}
      {{ prev.getLink() }}
    {% endif %}
  </nav>
{% endif %}
```

I will leave this open, because I think the relationship between these features is a valid thing to point out. Our priority will be updating 3.x and 4.x documentation, now, though!

**Comment by AugustMiller** [comment]
Just added a pagination section to the [Element Queries](https://craftcms.com/docs/4.x/element-queries.html#pagination) page.

Edit: `getNext()` and `getPrev()` are also now documented in the properties and methods section of the [Elements](https://craftcms.com/docs/4.x/elements.html#methods) page.
