### ISSUE TITLE
Docs site hangs for me in Firefox

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/docs#56]
### Description
Attempting to browse the site in Firefox (79.0 on Mac), and navigation hangs

I see javascript errors like 
> The resource from “https://craftcms.com/docs/assets/js/210.3cf6e775.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

and 

> Uncaught (in promise) ChunkLoadError: Loading chunk 210 failed.
> (error: https://craftcms.com/docs/assets/js/210.3cf6e775.js)

Works in Chrome

**Comment by mattstein** [comment]
Hi @marionnewlevant! Those chunks are generated with each new deploy and a refresh should immediately fix the problem. Does this persist for you regardless of the browser cache?

**Comment by mattstein** [comment]
Related: https://github.com/vuejs/vuepress/issues/2090

**Comment by mattstein** [comment]
Just tested new deployments that leave those older app bundles around and it seems to work nicely! You’ll still need to refresh to get the latest and greatest, but deployments should no longer disrupt an already-mounted VuePress instance. Closing and will re-evaluate if this turns out to have any weird side effects.
