### ISSUE TITLE
Improve “Commands”

### ISSUE THREAD

**Issue by nickwelsh1** [craftcms/docs#72]
I have a suggestion for https://craftcms.com/docs/nitro/commands.html

I'd add a note that for the `nitro ssh` command may need to be `winpty nitro ssh` instead on windows machines when using a Git Bash terminal (and perhaps other terminals?). I suspect if using a WSL terminal this may not be necessary?

**Comment by mattstein** [comment]
Thanks for pointing this out, @nickwelsh1!

`nitro ssh` seems to behave as expected with cmd.exe, PowerShell, and WSL—only Git Bash/MinGW needed `winpty` in order to get an interactive prompt. (Otherwise you’d get a glimpse of the machine prompt without any ability to interact with it, which I point out mostly for posterity since I’m sure you’re aware.)

Just [added a note to the Commands page](https://github.com/craftcms/docs/commit/fcc1d0e9c642346f5f456a57a54410370be9e70b) to clarify per your suggestion.
